---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: set hostname
      shell: |
       hostname "{{inventory_hostname}}"
       echo "{{inventory_hostname}}" > /etc/hostname
    - name: dhcp eth1
      shell: |
        ip addr show dev eth1 primary | grep inet || dhclient eth1
    - name: gather facts again
      setup:
    - name: install pacemaker stuff
      yum: name="{{ item }}" state=latest enablerepo=base
      with_items:
        - pcs
        - pacemaker
        - fence-agents-all
    - name: add hacluster user
      user:
        name: hacluster
        shell: /bin/bash
        password: $6$3Vsv/USdPcUl$ShL19F/R7QcTvgZxvgzLhNRn5Dspme06srj565UiQfYa2Q94or1qCBxjeb1XepAqVdHD7WzWm66CO0cFWFgaE/
    - name: Flush firewall
      iptables: flush=true
    - name: start services
      systemd: name="{{ item }}" state=started enabled=yes
      with_items:
        - pcsd
    - name: Create hostvars dump
      action: template src=templates/checkvars.j2 dest=/tmp/ansible.vars
    - name: Build hosts file
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_default_ipv4 is defined and hostvars[item].ansible_default_ipv4.address is defined
      with_items: "{{ groups['all'] }}"
