---
- name: set eth1 to dhcp
  copy:
    content: |
      DEVICE=eth1
      BOOTPROTO=dhcp
      ONBOOT=yes
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1

- name: bring eth1 up
  command: ifup eth1
  when: not (ansible_eth1.ipv4 is defined and ansible_eth1.ipv4.address is defined)

