---
- name: Generate xapissl.pem
  command: /opt/xensource/libexec/generate_ssl_cert /etc/xensource/xapi-ssl.pem {{inventory_hostname}}

- name: Add local-port to xapi-clusterd service file
  lineinfile:
    path: /usr/lib/systemd/system/xapi-clusterd.service
    regexp: '^ExecStart=/usr/sbin/xapi-clusterd$'
    line: 'ExecStart=/usr/sbin/xapi-clusterd --local_port 8895'

- name: Open port 8895 in the firewall
  lineinfile:
    path: /etc/sysconfig/iptables
    insertafter: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 8892 -j ACCEPT'
    line: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 8895 -j ACCEPT'

- name: Restart iptables to pick up the new rule
  systemd: state=restarted enabled=yes name=iptables

# Note: if upgrading a live system would need to stop the cluster or at least disable fencing first
- name: Run xapi-clusterd
  systemd: state=started enabled=yes name=xapi-clusterd

# We are going to fence in the tests, make sure we don't loose all the
# provisioning after a reboot
- name: Sync
  command: sync
