---
- name: disable XAPI-NBD path activation
  systemd: enabled=no masked=yes name=xapi-nbd.path

- name: disable ntpdate
  systemd: enabled=no masked=yes name=ntpdate

- name: Generate xapissl.pem
  command: /opt/xensource/libexec/generate_ssl_cert /etc/xensource/xapi-ssl.pem {{inventory_hostname}}
  args:
    creates: /etc/xensource/xapi-ssl.pem

- name: Add local-port to xapi-clusterd service file
  lineinfile:
    path: /usr/lib/systemd/system/xapi-clusterd.service
    regexp: '^ExecStart=/usr/sbin/xapi-clusterd'
    line: 'ExecStart=/usr/sbin/xapi-clusterd --local_port 8895'

- name: Open port 8895 and 8896 in the firewall
  command: "/etc/xapi.d/plugins/firewall-port open {{ item }}"
  with_items:
      - 8895
      - 8896

# Note: if upgrading a live system would need to stop the cluster or at least disable fencing first
- name: Run xapi-clusterd
  systemd: state=started enabled=yes name=xapi-clusterd

# We are going to fence in the tests, make sure we don't loose all the
# provisioning after a reboot
- name: Sync
  command: sync
