---
# Note: if upgrading a live system would need to stop the cluster or at least disable fencing first
- name: install pacemaker stuff
  yum: name="{{ item }}" state=latest enablerepo=base,updates
  with_items:
    - corosync
    - dlm
    - pcs
    - pacemaker
    - fence-agents-all
    - sbd
    - iptables-services
- name: load watchdog module on boot
  lineinfile:
    dest: /etc/modules-load.d/watchdog.conf
    line: xen_wdt
    state: present
    create: true
- name: load watchdog now
  modprobe:
      name: xen_wdt
      state: present
- name: add hacluster user
  user:
    name: hacluster
    shell: /bin/bash
    password: $6$3Vsv/USdPcUl$ShL19F/R7QcTvgZxvgzLhNRn5Dspme06srj565UiQfYa2Q94or1qCBxjeb1XepAqVdHD7WzWm66CO0cFWFgaE/
- name: Flush firewall
  iptables: flush=true
  notify:
    - save iptables
- name: start services
  systemd: name="{{ item }}" state=started enabled=yes
  with_items:
    - pcsd
- meta: flush_handlers # run all handlers, e.g. if initiatorname was changed
- name: setup local iSCSI
  open_iscsi:
    portal: "{{hostvars['infrastructure'].ansible_ssh_host}}"
    login: yes
    discover: yes
    show_nodes: yes

