---
- name: Generate xapissl.pem
  command: /opt/xensource/libexec/generate_ssl_cert /etc/xensource/xapi-ssl.pem {{inventory_hostname}}

# Note: if upgrading a live system would need to stop the cluster or at least disable fencing first
- name: Run xapi-clusterd
  systemd: state=started enabled=yes name=xapi-clusterd

# We are going to fence in the tests, make sure we don't loose all the
# provisioning after a reboot
- name: Sync
  command: sync
