---
- name: set hostname
  shell: |
    hostname "{{inventory_hostname}}"
    echo "{{inventory_hostname}}" > /etc/hostname
  when: ansible_hostname != inventory_hostname
- name: speed up boot - disable boot timeout
  lineinfile:
    path: /boot/grub/grub.cfg
    regexp: '^set timeout='
    line: 'set timeout=0'
- name: remove non-local NTP servers
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server.*ntp.org'
    state: absent
- name: remove step-tickers to force ntp.conf fallback
  file:
      path: /etc/ntp/step-tickers
      state: absent
- name: improve log timestamps
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^\$ActionFileDefaultTemplate '
    line: '$ActionFileDefaultTemplate RSYSLOG_FileFormat'
  notify:
    - restart syslog
- name: Find RPMs
  find:
    paths: "/rpms"
    patterns: "*.rpm"
  register: find_result
- name: Upgrade RPMs
  shell: |
    rpm -Uvh --force "{{ item.path }}" --nodeps && rm "{{ item.path }}"
  with_items: "{{ find_result.files }}"

