---
- name: set hostname
  shell: |
    hostname "{{inventory_hostname}}"
    echo "{{inventory_hostname}}" > /etc/hostname
  when: ansible_hostname != inventory_hostname
- name: gather facts again
  setup:
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4 is defined and hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
